### ISSUE TITLE
Periodic tasks?

### ISSUE THREAD

**Issue by tonycpsu** [ask/flask-celery#16]
I haven't found an obvious way to do periodic tasks with flask-celery 2.4.1 (with Celery 2.4.6 and Flask 0.8.).  I thought using @celery.periodic_task decorator syntax might work, but it doesn't, and neither does "from celery.task import periodic_task."

Are periodic tasks supported?  I see mention of the module starting the periodic task scheduler, but can't figure out how to use it.

Thanks.

**Comment by ask** [comment]
They are supported, use `CELERYBEAT_SCHEDULE`: http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#entries

`PeriodicTask`/`@periodic_task` just adds itself to that setting anyway, and they are no longer documented.

**Comment by tonycpsu** [comment]
OK, that works -- thanks.

**Comment by xiapoy** [comment]
@tonycpsu @ask I have some issues trying to integrate the `CELERYBEAT_SCHEDULE:` to my existing flask app. I added it in my app settings file but it does not seems to work.

```
app = Flask(__name__)
Bootstrap(app)
app.config.from_object(settings)

def make_celery(app):
    celery = Celery(app.import_name, broker=app.config['CELERY_BROKER_URL'])
    celery.conf.update(app.config)
    TaskBase = celery.Task
    class ContextTask(TaskBase):
        abstract = True
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)
    celery.Task = ContextTask
    return celery

celery = make_celery(app)

@celery.task(name='background_task')
def background_task(url):
    req = urllib2.Request(url)
    count = urllib2.urlopen(req).read()
    if count == '0':
        running = pb.push_note('running')
    else:
        done = pb.push_note('done')
```

And then, in my separate app settings file, I've added the  `CELERYBEAT_SCHEDULE`

```
from datetime import timedelta

SECRET_KEY='not_a_secret'
CELERY_BROKER_URL='redis://localhost:6379/0',
CELERY_RESULT_BACKEND='redis://localhost:6379/0'
CELERYBEAT_SCHEDULE = {
    'add-every-30-seconds': {
        'task': 'background_task',
        'schedule': timedelta(seconds=30),
        'args': (16, 16)
    },
}

CELERY_TIMEZONE = 'UTC'
```

But it seems the celery task only runs once instead of every 30 seconds. Can you provide some insights about how you made it to work with your app ? Many thanks !
