### ISSUE TITLE
Feature Request: App Factory Support

### ISSUE THREAD

**Issue by imlucas** [ask/flask-celery#6]
The current implementation works great for small single module apps, but when you start using application factories (http://flask.pocoo.org/docs/patterns/appfactories/) and several modules, things don't really work.  Say you have a tasks module like so https://gist.github.com/816650.  If you're imports aren't exactly right in a black magic kind of way, this will blow up every single time.  Is there a better way to do this I'm just missing?

-Lucas

**Comment by imlucas** [comment]
I thought about this a lot more over the past several weeks.  Think a good solution may be using the init_app pattern.  That is celery.task adds the def to a queue stack that only exists in the extension.  When init_app is called (either via the extension construction case or inside create_app, the tasks will actually be bound to the real celery app object). Will play around with it in my fork.

**Comment by thadeusb** [comment]
+1 to implement.

**Comment by ask** [comment]
Cool, do you have anything I can look at yet? :)

**Comment by albarrentine** [comment]
With "The Big Instance Refactor" from celery 2.3.3+ (http://ask.github.com/celery/internals/app-overview.html), I got it working out of the box.

Example: 
https://gist.github.com/1326477

The ability to just say celery = Celery(); Task = celery.create_task_cls(); and then configure it later is awesome. Just as long as you treat that celery.app.App instance the way you'd treat an unbound SQLAlchemy session (i.e. don't expect any of the config info at import time - which you shouldn't do anyway) then it works fine.

**Comment by imlucas** [comment]
I have yet to come up with anything as easy or clean as just putting the imports and apply_async calls in blinker signals.  Thanks Al.  We're on 2.3.1 now.  I'll give 2.3.3+ a try when I get some more time.

**Comment by imlucas** [comment]
Decided to revisit after upgrading to celery 2.4.6.  Al's solution didn't work correctly in all cases for us, just sent #15 which I think finally has a solution.
